### PR TITLE
Fix: bug with >1 admonition block 

### PR DESCRIPTION
**Pull request by ianfhunter**
If you have >1 admonition block in a note, and a logo/title is injected - offsets were then incorrect.

Now, whenever a title/logo is injected, the start/end offsets for the block are adjusted.

+ some small code improvements + typo fixes

### CODE REVIEW

**Comment by Mara-Li** [comment]
Thank you a lot for your work !

**Comment by Mara-Li** [comment]
Ah just a little information, about "example" and "exemple"
Exemple, is... The word in french, and sometimes I tip "exemple" instead of "example" in my admonition and I added a special admonition for that.

**Comment by ianfhunter** [comment]
Ah, I see! I assumed it was a typo :)

**Comment by Mara-Li** [comment]
Well, I have some problem (a lot) with your work on admonition : I always have "none type". I think you forgot to add some check in the research.

File for test : 
https://gist.githubusercontent.com/Mara-Li/771b71a06fed93a3e9ed472b0de5847e/raw/d05a655004b7363798f9af7a07a7937ce569ddbf/test_file_admo

**Comment by ianfhunter** [comment]
Ah, I think I did not push the second commit!

**Comment by ianfhunter** [comment]
`offset_for_title = 1`
Should be
`offset_for_title += 1`

It is night right now for me, I will test it with your file in the morning

**Comment by Mara-Li** [comment]
I will check ! 👍 
Thank you for your work and interest !

**Comment by Mara-Li** [comment]
Okay ! 
So your correction is good. 
I take some times to correct some things. First, the JS.
Also, I correct the list that doesn't work with this trick. Now, the `-` ; `+` ; `*` are rendered with `**•**{: .bullet}` (it's the first Idea that come my mind).
I also add `.bullet` class  :
```css
.bullet {
    font-size: 24px;
    vertical-align: -1%;
}
```

**Comment by Mara-Li** [comment]
Last update : I create a Yaml file in the blog repo to add the possibility for custom ADMONITION!

**Comment by ianfhunter** [comment]
Great! :)

**Pull request merged**
