### PR TITLE
Support '~' and an alternative image form

### PR DESCRIPTION
**Pull request by ianfhunter**
- Allow ~ directories in config
- Correct check for empty items
- support markup image format like `alt_image `
  - solves a crash
  - happens sometimes when copy pasting stuff

### CODE REVIEW

**Comment by Mara-Li** [comment]
I need to check if the expand user will work on IOS but thank you for this 🎉

**Comment by ianfhunter** [comment]
I just tested on Linux so that would be great 👍 
Thank you for the library ❤️

**Comment by Mara-Li** [comment]
Some things on IOS with a-shell are strange so... I will try this night !

**Comment by Mara-Li** [comment]
Okay, I'm sorry, but, after some try, the image transform seems to have problem. 


See below : 
image
With your version.

With my version : No bug.
Also, testing with my version : 
image
image

Did you check if your file name have space ? Space must be replaced by %20 in obsidian.

**Comment by ianfhunter** [comment]
Hmm, I will try to reproduce it next week
My file name was a URL and it caused the program to crash before my PR

`AltText`

I think maybe you are right, that the regex may need updating for spaces

**Comment by Mara-Li** [comment]
I test and I have no crash at all :O
image

**Comment by ianfhunter** [comment]
:o 

Let me see if I can build a minimal test case and I'll reopen a PR if I need to. Hopefully it was just... A ghost? 👻

**Comment by Mara-Li** [comment]
Maybe you used an old version !

**Pull request merged**
